
[tool.black]
line-length = 88
target-version = ["py313"]

[tool.ruff]
line-length = 88
target-version = "py313"
extend-exclude = [
    ".venv",
    "venv",
    "build",
    "dist",
    "node_modules",
    "chroma_db",
    ".mypy_cache",
    ".pytest_cache",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line length handled by formatter (black)
]
fixable = [
    "ALL",
]
unfixable = [
]

[tool.ruff.lint.per-file-ignores]
"tgbot/locales/*.py" = ["E501"]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true
suppress-dummy-args = false
allow-star-arg-any = false
ignore-fully-untyped = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.mypy]
python_version = "3.13"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = false
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = [
    "^tests/",
    "^chroma_db/",
    "^venv/",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"

testpaths = [
    "tests",
]
asyncio_mode = "auto"
pythonpath = ["."]
asyncio_default_fixture_loop_scope = "function"
log_cli = true
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.semantic_release]
version_variable = [
    "agentsmithy_server/__init__.py:__version__",
]
branch = "master"
upload_to_vcs_release = true
build_command = false
commit_message = "chore(release): {version} [skip ci]"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.changelog]
exclude_commit_patterns = []

[tool.semantic_release.branches.master]
match = "master"
prerelease = false


